---
###########################################################
# Playbook to install and configure Apache and PHP  TASK  ##
# #########################################################

# Create a playbook ~/playbooks/httpd.yml on jump host and perform the following tasks on App Server 1.

# a. Install httpd and php packages (whatever default version is available in yum repo).

# b. Change default document root of Apache to /var/www/html/myroot in default Apache config /etc/httpd/conf/httpd.conf. Make sure /var/www/html/myroot path exists (if not please create the same).

# c. There is a template ~/playbooks/templates/phpinfo.php.j2 on jump host. Copy this template to the Apache document root you created as phpinfo.php file and make sure user owner and the group owner for this file is apache user.

# d. Start and enable httpd service.

- name: Install httpd & PHP
  hosts: stapp01
  become: yes
  tasks:
  - yum: name=httpd state=installed
  - yum: name=php state=installed

  - name: Create document root file
    file:
      path: "/var/www//html/myroot/"
      state: directory
      owner: apache
      group: apache

  - copy:
      src: ~/playbooks/templates/phpinfo.php.j2
      dest: /var/www/html/myroot/phpinfo.php
      owner: apache
      group: apache

  - lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^DocumentRoot "/var/www/html"'
      line: 'DocumentRoot "/var/www/html/myroot"'
      state: present
  - service:
      name: httpd
      state: started
      enabled: yes
